config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'pages/introduce'
  get 'pages/support'
  get 'pages/foods'
  get 'pages/drinks'
  get 'pages/purchased_orders'
  get 'admin/dashboard'
  get 'admin/warehouse'
  get 'admin/reportlist' 

  devise_for :users
  
  scope "/admin" do
    resources :users, only: [:index, :edit, :update, :destroy]
  end
  
  resources :products do
    resources :cart_items
    resources :reviews
  end
  
  resources :carts, only: [:show] do
    resources :cart_items, except: [:update]
  end
  
  resources :orders

  patch "cart/cart_item" => "cart_items#update"
  patch "cart-update" => "carts#update"
  get '/products/:id/details', to: 'products#details', as:'product-details'
end

app/views/admin/_category.html.erb
<div class="d-flex justify-content-center">
    <%= link_to "All", admin_warehouse_path, class:"btn btn-outline-secondary rounded-pill mx-2 px-4" %>
    <%= button_to "Foods", admin_warehouse_path, method: :get, params: { product_type_tag: "food" }, class:"btn btn-outline-secondary rounded-pill mx-2 px-4" %>
    <%= button_to "Drinks", admin_warehouse_path, method: :get, params: { product_type_tag: "drink" }, class:"btn btn-outline-secondary rounded-pill mx-2 px-4" %>
</div>

app/views/admin/_chart.html.erb
<div class="my-4"><%= column_chart @orders.group_by_day_of_week(:created_at ,format: "%a").sum(:total),thousands: ",",  xtitle: "Doanh thu" %></div>

app/views/admin/_filter_form.html.erb
<div class="d-flex justify-content-center mb-3">
  <%= form_for(:search, class: 'form-group', url: admin_reportlist_path , method: :get) do |f| %>
    <div class="form-group mt-3 d-flex">
      <%= f.text_field :created_at, data: { behavior:'daterangepicker' }, value: created_at_from_parameters, class: 'ps-3', style:"width:600px" %>
      <%= f.submit "Tim kiem", class:"btn btn-success ms-1"%>
    </div>
  <%end%>
</div>

app/views/admin/_item.html.erb
 <tr>
  <th scope="row "><%= stt %></th>
  <td><%= product.title %></td>
  <td><%= product.product_type.upcase %></td>
  <td><%= product.quantity + product_sold_quantity(product) %></td>
  <td><%= product.quantity %></td>   
  <td><%= product_sold_quantity(product) %></td>
 </tr>

app/views/admin/_reportfilter.html.erb
<div class="d-flex justify-content-center">
    <%= button_to "Hôm nay", admin_reportlist_path, method: :get, class:"btn btn-outline-secondary rounded-pill mx-2 px-2 py-0" %>
    <%= button_to "Hôm qua", admin_reportlist_path, method: :get, params: { option: "yesterday" }, class:"btn btn-outline-secondary rounded-pill mx-2 px-2 py-0" %>
    <%= button_to "Tuần này", admin_reportlist_path, method: :get, params: { option: "week" }, class:"btn btn-outline-secondary rounded-pill mx-2 px-2 py-0" %>
    <%= button_to "Tuần trước", admin_reportlist_path, method: :get, params: { option: "lastweek" }, class:"btn btn-outline-secondary rounded-pill mx-2 px-2 py-0" %>
    <%= button_to "Tháng này", admin_reportlist_path, method: :get, params: { option: "month" }, class:"btn btn-outline-secondary rounded-pill mx-2 px-2 py-0" %>
</div>

app/views/admin/dashboard.html.erb
<div class="container">
  <h1 class="text-center mt-4 mb-2">ADMIN DASHBOARD</h1>

  <div class="mb-5" id="dashboard">

    <div class="row d-flex justify-content-center my-3">
      <div class="card pt-2 border border-4 rounded-circle border-primary">
        <%= link_to users_path, class:"text-decoration-none" do %>
          <div class="card-body d-flex flex-column justify-content-center align-items-center">
            <h1><i class="fas fa-users text-primary display-5"></i></h1>
            <h5 class="card-title text-primary fst-italic">Users</h5>
          </div>
        <% end %>
      </div>
    </div>

    <div class="row d-flex justify-content-center" style="margin-bottom:60px">
      <div class="card pt-2 border border-4 rounded-circle border-warning">
        <%= link_to products_path, class:"text-decoration-none" do %>
          <div class="card-body d-flex flex-column justify-content-center align-items-center">
            <h1><i class="fas fa-cubes text-warning display-5"></i></h1>
            <h5 class="card-title text-warning fst-italic">Products</h5>
          </div>
        <% end %>
      </div>
      <span style="width:16%"></span>
      <div class="card pt-2 border border-4 rounded-circle border-danger">
        <%= link_to orders_path, class:"text-decoration-none" do %>
          <div class="card-body d-flex flex-column justify-content-center align-items-center">
            <h1><i class="fas fa-file-invoice-dollar text-danger display-5"></i></h1>
            <h5 class="card-title text-danger fst-italic">Orders</h5>
          </div>
        <% end %>
      </div>
    </div>

    <div class="row d-flex justify-content-center">
      <div class="card pt-2 border border-4 rounded-circle border-success">
        <%= link_to admin_warehouse_path, class:"text-decoration-none" do %>
          <div class="card-body d-flex flex-column justify-content-center align-items-center">
          <h1><i class="fas fa-warehouse text-success display-5"></i></h1>
          <h5 class="card-title text-success fst-italic">Warehouse</h5>
          </div>
        <% end %>
      </div>
      <span style="width:7%"></span>
      <div class="card pt-2 border border-4 rounded-circle border-info">
        <%= link_to admin_reportlist_path, class:"text-decoration-none" do %>
          <div class="card-body d-flex flex-column justify-content-center align-items-center">
          <h1><i class="fas fa-chart-line text-info display-5"></i></h1>
          <h5 class="card-title text-info fst-italic">Income</h5>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/admin/reportlist.html.erb
<div class="container mb-5" style="min-height:600px">
  <div class="text-center mt-4 mb-3">
    <% if @beginning_day.to_date != @end_day.to_date %>
      <p class="fs-3 fst-italic">Báo cáo doanh thu từ <b><%=@beginning_day.strftime("%d/%m/%Y")%></b> đến <b><%=@end_day.strftime("%d/%m/%Y")%></b></p>
    <% else %>
      <p class="fs-3 fst-italic">Báo cáo doanh thu ngày <b><%=@beginning_day.strftime("%d/%m/%Y")%></b></p>
    <% end %>
  </div>
  
  <div class="mb-4">
    <%= render "filter_form" %>
    <%= render "reportfilter"%>
    <%= render "chart"%>
  </div>

  <% if @orders.count > 0 %>
    <table class="table table-striped">
      <thead>
        <tr class="fs-5">
          <th scope="col">Mã đơn hàng</th>
          <th scope="col">Ngày mua</th>
          <th scope="col" class="text-center">SL Sản phẩm</th>
          <th scope="col" class="text-center">Email đặt hàng</th>
          <th scope="col" class="text-end pe-5">Tổng tiền</th>
        </tr>
      </thead>
      <tbody>
         <tr class="bg-success">
          <th scope="col" class ="text-light">Tổng HĐ: <%= @orders.count%></th>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col" class ="text-light text-end pe-5"><%= number_to_currency(@total_report, unit:"", precision: 0, delimiter:'.') %>đ</th>
        </tr>
        <% @orders.each do |order| %>
          <tr>
            <th scope="row" class="ps-4 py-3"><%= link_to "HD%04d"%[order.id], order_path(order), class:"text-decoration-none" %></th>
            <td><%= order.created_at.strftime("%d-%m-%Y") %></td>
            <td class="text-center"><%= order.order_items.count %></td>
            <td class="text-center"><%= order.user.email %></td>
            <td class="text-end pe-5"><%= number_to_currency(order.total, unit:"", precision: 0, delimiter:'.') %>đ</td>
          </tr>
        <% end %>
      </tbody>  
    </table>
    <div class="apple_pagination">
      <%= will_paginate @orders, :container => false %>
    </div>
  <% else %>
    <p class="fs-4 ms-4 mt-4">Oh! Bạn không có đơn hàng nào cả.</p>
  <% end %>
</div>

<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

app/views/admin/warehouse.html.erb
<div class="container mb-5">
  <h1 class="text-center my-4">Quản lý kho</h1>

  <div class="d-flex justify-content-between mb-4">
    <%= render "category" %>
    <%= render "shared/search_form", path: admin_warehouse_path %>
  </div>


  <% if @products.count > 0 %>
    <table class="table colorloeloet table-striped " >
      <thead>
        <tr>
          <th scope="col">STT</th>
          <th scope="col" style="width:40%">Tên SP</th>
          <th scope= "col">Phân loại</th>
          <th scope = "col"> Tổng SL </th>
          <th scope="col">SL tồn kho</th>
          <th scope = "col">SL Bán</th>
        </tr>
      </thead>
      <tbody>
        <% stt = 1 %>
        <% @products.each do |product| %>
          <%= render 'item', product: product, stt: stt %>
          <% stt += 1 %>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="fs-4 ms-4 mt-4">Cannot find any products</p>
  <% end %>
  
  <div class="apple_pagination">
    <%= will_paginate @products, :container => false %>
  </div>
</div>