config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'pages/introduce'
  get 'pages/support'
  get 'pages/foods'
  get 'pages/drinks'
  get 'pages/purchased_orders'
  get 'admin/dashboard'
  get 'admin/warehouse'
  get 'admin/reportlist' 

  devise_for :users
  
  scope "/admin" do
    resources :users, only: [:index, :edit, :update, :destroy]
  end
  
  resources :products do
    resources :cart_items
    resources :reviews
  end
  
  resources :carts, only: [:show] do
    resources :cart_items, except: [:update]
  end
  
  resources :orders

  patch "cart/cart_item" => "cart_items#update"
  patch "cart-update" => "carts#update"
  get '/products/:id/details', to: 'products#details', as:'product-details'
end

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h2>The following errors prevented the <%= obj.model_name.human.downcase %> from being saved</h2>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_filter_form.html.erb
<div class="d-flex filter-form">
  <%= button_to "Giá tăng dần", path, method: :get, params: { option: "price_asc" }, class:"button btn-increase" %>
  <%= button_to "Giá giảm dần", path, method: :get, params: { option: "price_desc" }, class:"button btn-descrease" %>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= flash_class_name(name) %> mb-0" role="alert">
    <div class="mx-4">
      <%= msg %>
      <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-5 bg-dark text-white-50">
  <div class="container text-center">
    Copyright &copy; Team2 - Ruby on Rails Intern
  </div>
</footer>

<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

<script>
  $(function() {
    $('[data-behavior=daterangepicker]').daterangepicker({
        locale: { format: 'DD/MM/YYYY' },
        cancelLabel: 'Clear'
    });

    $('[data-behavior=daterangepicker]').on('cancel.daterangepicker', function() {
        $(this).val(' ');
    });
  });
</script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark py-4">
  <div class="container-fluid">
    <h2><%= link_to "T2FoodStore", root_path, class: "navbar-brand" %></h2>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Trang Chủ", root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Món Chính", pages_foods_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Thức Uống", pages_drinks_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Giới Thiệu", pages_introduce_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Hỗ Trợ", pages_support_path, class:"nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav mb-2 me-4 mb-lg-0 d-flex">
        <% if user_signed_in? %>
          <% create_new_cart(current_user) %>
          <i class="far fa-user fs-3 text-secondary mt-1"></i>
          <li class="nav-item dropdown me-3">
            <a class="nav-link px-3 dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.username %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li class="pe-5"><small><%= link_to "Thông tin tài khoản", edit_user_registration_path, class:"dropdown-item" %></small></li>
              <li><small><%= link_to "Đơn hàng của tôi", pages_purchased_orders_path, class:"dropdown-item" %></small></li>
              <% if current_user.admin? %>
                <li><small><%= link_to "Admin dashboard", admin_dashboard_path, class:"dropdown-item" %></small></li>
              <% end %>
              <li><hr class="dropdown-divider"></li>
              <li><small><%= button_to "Thoát tài khoản", destroy_user_session_path, method: :delete, class:"dropdown-item" %></small></li>
            </ul>
          </li>
          <li class="nav-item" id="shoppingCart">
            <%= link_to cart_path(current_user.cart), class:"refresh" do %>
              <i class="fas fa-shopping-basket fs-3 text-secondary mt-1 me-4">
                <span class="<%= "disabled" if current_user.cart.cart_items.empty? %>"><%= current_user.cart.cart_items.count %></span>
              </i>
            <% end %>
          </li>
        <% else %>
          <i class="far fa-user fs-3 text-secondary mt-1 me-3"></i>
          <li class="nav-item me-4">
            <small><%= link_to "Đăng Nhập / Đăng Ký", new_user_session_path, class:"nav-link px-0" %></small>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path do %>
              <i class="fas fa-shopping-basket fs-3 text-secondary mt-1 me-4"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
      <li class="dropdown">
      <%= link_to "#!", class: "dropdown-toggle", id: "noti-count", data: {toggle: "dropdown"},
        aria: {haspopup: "true", expanded: "false"} do %>
        <span class="fa fa-globe"></span>
        <span class="badge badge-danger" data-noti-count="<%= user_signed_in? ? current_user.notifications.num_not_check : 0 %>">
          <%= user_signed_in? ? current_user.notifications.num_not_check : 0 %>
        </span>
        <span class="caret"></span>
      <% end %>
      <% if user_signed_in? %>
        <ul class="dropdown-menu dropdown-notification scrollable-menu" id="user-notifications">
          <%= render current_user.notifications %>
        </ul>
      <% end %>
      </li>
    </div>
  </div>
</nav>

app/views/shared/_product.html.erb
<div class="col ms-2 mb-3">
  <div class="card mb-3" style="width: 18rem;">
    <img class="card-img-top" src="<%= product.image_url %>" alt="image.jpg">
    <div class="card-body">
      <h5 class="card-title"><%= truncate product.title, length:27 %></h5>
      <p class="card-text text-success fs-5 mb-1"><%= number_to_currency(product.price, unit:"", precision: 0, delimiter:'.') %> đ</p>
      <%= button_to "Đặt Món", product_details_path(product), method: :get, params: { product_id: product.id }, class: "btn btn-success float-end" %>
    </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<%= form_tag(path, method: :get, class: "d-flex search-form") do %>
  <%= text_field_tag(:term, params[:term], placeholder: "Tìm sản phẩm", class:"search-input") %>
  <%= submit_tag('Tìm kiếm', class:"search-submit") %>
<% end %>